name: BioML-tut-llm
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=20.1.5
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.4.0
  - readline=8.2
  - setuptools=80.1.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - absl-py==2.2.2
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.85
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepspeed==0.16.7
      - discrete-key-value-bottleneck-pytorch==0.1.1
      - dllogger==1.1.0
      - dm-tree==0.1.9
      - einops==0.8.1
      - einx==0.3.0
      - enformer-pytorch==0.8.10
      - fair-esm==2.0.0
      - filelock==3.18.0
      - fonttools==4.58.0
      - frozendict==2.4.6
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - hjson==3.1.0
      - huggingface-hub==0.31.2
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - lightning-utilities==0.14.3
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==2.2.5
      - omegaconf==2.3.0
      - pandas==2.2.3
      - pillow==11.2.1
      - polars==1.29.0
      - propcache==0.3.1
      - ptflops==0.7.4
      - py-cpuinfo==9.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyfaidx==0.8.1.4
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rna-fm==0.2.2
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - transformers==4.51.3
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - vector-quantize-pytorch==1.22.16
      - wrapt==1.17.2
      - yarl==1.20.0
